class_name SpeedData

enum SKILL {BEGGINER,INTERMEDIATE,ADVANCED,ACC}

#TODO convert to prototype floats
const BASE_SPEED:float =  18.4#12950.0

#PERCENTAGES

const PERCENTAGE_MT_1:float = 1.158146718
const PERCENTAGE_MT_2:float = 1.197683398
const PERCENTAGE_MT_3:float = 1.237220077
const PERCENTAGE_SF:float = 1.316293436

const PERCENTAGE_SPEED_INTERMEDIATE:float = 0.014671815 * BASE_SPEED
const PERCENTAGE_SPEED_ADVANCED:float = 0.073359073 * BASE_SPEED
const PERCENTAGE_SPEED_ACC:float = 0.044015444 * BASE_SPEED


#SPEED
const BEGGINER_SPEED:float = BASE_SPEED
const INTERMEDIATE_SPEED:float = BASE_SPEED + PERCENTAGE_SPEED_INTERMEDIATE
const ADVANCED_SPEED:float = BASE_SPEED + PERCENTAGE_SPEED_ADVANCED
const ACC_SPEED:float = BASE_SPEED + PERCENTAGE_SPEED_ACC

#SKILL INDEPENDANT SPEED

const USF_SPEED:float = (BASE_SPEED * 97.68339768 * 0.01)
const GHOST_SPEED:float = 0.0 #TODO

#POWER SLIDE

# beginner
const BEGGINER_MT_1:float = PERCENTAGE_MT_1 * BEGGINER_SPEED
const BEGGINER_MT_2:float = PERCENTAGE_MT_2 * BEGGINER_SPEED
const BEGGINER_MT_3:float = PERCENTAGE_MT_3 * BEGGINER_SPEED
const BEGGINER_SF:float = PERCENTAGE_SF * BEGGINER_SPEED

# intermediate
const INTERMEDIATE_MT_1:float = PERCENTAGE_MT_1 * INTERMEDIATE_SPEED
const INTERMEDIATE_MT_2:float = PERCENTAGE_MT_2 * INTERMEDIATE_SPEED
const INTERMEDIATE_MT_3:float = PERCENTAGE_MT_3 * INTERMEDIATE_SPEED
const INTERMEDIATE_SF:float = PERCENTAGE_SF * INTERMEDIATE_SPEED

# acc
const ACC_MT_1:float = PERCENTAGE_MT_1 * ACC_SPEED
const ACC_MT_2:float = PERCENTAGE_MT_2 * ACC_SPEED
const ACC_MT_3:float = PERCENTAGE_MT_3 * ACC_SPEED
const ACC_SF:float = PERCENTAGE_SF * ACC_SPEED

#advanced
const ADVANCED_MT_1:float = PERCENTAGE_MT_1 * ADVANCED_SPEED
const ADVANCED_MT_2:float = PERCENTAGE_MT_2 * ADVANCED_SPEED
const ADVANCED_MT_3:float = PERCENTAGE_MT_3 * ADVANCED_SPEED
const ADVANCED_SF:float = PERCENTAGE_SF * ADVANCED_SPEED

static func get_skill(skill:int) -> Dictionary:
	match skill:
		SKILL.BEGGINER:
			return {
				_min = BEGGINER_SPEED,
				_mt1 = BEGGINER_MT_1,
				_mt2 = BEGGINER_MT_2,
				_mt3 = BEGGINER_MT_3,
				_sf = BEGGINER_SF
			}
		SKILL.ADVANCED:
			return {
				_min = ADVANCED_SPEED,
				_mt1 = ADVANCED_MT_1,
				_mt2 = ADVANCED_MT_2,
				_mt3 = ADVANCED_MT_3,   
				_sf = ADVANCED_SF,
			}
	return {}
